# Generated by Django 5.2.9 on 2025-12-30 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('fase', models.CharField(choices=[('A', 'Fase A'), ('B', 'Fase B'), ('C', 'Fase C')], max_length=10)),
                ('aktif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mengajar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun_ajaran', models.CharField(max_length=20)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.guru')),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.kelas')),
                ('mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.mapel')),
            ],
            options={
                'unique_together': {('guru', 'mapel', 'kelas', 'tahun_ajaran')},
            },
        ),
        migrations.CreateModel(
            name='Nilai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('Ganjil', 'Ganjil'), ('Genap', 'Genap')], max_length=10)),
                ('tahun_ajaran', models.CharField(max_length=20)),
                ('nilai_formatif', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('nilai_sumatif', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('catatan', models.TextField(blank=True)),
                ('guru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='akademik.guru')),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.kelas')),
                ('mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.mapel')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.siswa')),
            ],
            options={
                'unique_together': {('siswa', 'mapel', 'kelas', 'semester', 'tahun_ajaran')},
            },
        ),
    ]
