# Generated by Django 5.2.9 on 2026-01-01 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0002_mapel_mengajar_nilai'),
    ]

    operations = [
        migrations.AddField(
            model_name='guru',
            name='jk',
            field=models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], default='L', max_length=1),
        ),
        migrations.AddField(
            model_name='guru',
            name='tanggal_lahir',
            field=models.DateField(blank=True, null=True),
            preserve_default=False,
        ),
    ]
