# Generated by Django 5.2.9 on 2026-01-01 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0003_guru_jk_guru_tanggal_lahir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guru',
            name='tanggal_lahir',
            field=models.DateField(blank=True, null=True),
        ),
    ]
