# Generated by Django 5.2.9 on 2025-12-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('kepsek', 'Kepala Sekolah'), ('guru', 'Guru'), ('tu', 'Tata Usaha'), ('bendahara', 'Bendahara')], default='guru', max_length=20),
        ),
    ]
