# Generated by Django 5.2.9 on 2025-12-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'SUPERADMIN'), ('kepsek', 'Kepala Sekolah'), ('guru', 'Guru'), ('tu', 'Tata Usaha'), ('bendahara', 'Bendahara')], default='guru', max_length=20),
        ),
    ]
