# Generated by Django 5.2.9 on 2026-01-01 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('akademik', '0004_alter_guru_tanggal_lahir'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ekskul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('aktif', models.BooleanField(default=True)),
                ('pembina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='akademik.guru')),
            ],
        ),
        migrations.CreateModel(
            name='Pelanggaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jenis', models.CharField(max_length=100)),
                ('poin', models.PositiveIntegerField(default=0)),
                ('keterangan', models.TextField(blank=True)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.siswa')),
            ],
        ),
        migrations.CreateModel(
            name='Prestasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(max_length=100)),
                ('tingkat', models.CharField(max_length=50)),
                ('tahun', models.CharField(max_length=10)),
                ('keterangan', models.TextField(blank=True)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.siswa')),
            ],
        ),
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('status', models.CharField(choices=[('H', 'Hadir'), ('I', 'Izin'), ('S', 'Sakit'), ('A', 'Alpha')], max_length=1)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absensi', to='akademik.guru')),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.kelas')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.siswa')),
            ],
            options={
                'unique_together': {('siswa', 'tanggal')},
            },
        ),
        migrations.CreateModel(
            name='AnggotaEkskul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun_ajaran', models.CharField(max_length=20)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.siswa')),
                ('ekskul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kesiswaan.ekskul')),
            ],
            options={
                'unique_together': {('siswa', 'ekskul', 'tahun_ajaran')},
            },
        ),
    ]
